[build]
  base = "countdown-app"
  command = "npm run build"
  publish = "dist/countdown/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle Angular routing
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
